accountTypeChangeTimeout: ' &8>> &cRequest timed out!'
addNewEmailAddressCommand: ' &8>>Add your email adress! &cUse &e/email <email-address>!'
addressAlreadyWhitelisted: '&cThis address is already whitelisted.'
addressInNotWhitelisted: '&cThis address is not whitelisted.'
addressIsNotValid: '&cThis address is not valid.'
adminCommand:
  -  ' &8>> &c/minelogin version - &ePlugin version information.'
  -  ' &8>> &c/minelogin reload - &eReload plugin configs.'
  -  ' &8>> &c/minelogin userinfo <username> - &eReturn information about user.'
  -  ' &8>> &c/minelogin register <username> <password> - &eRegister user.'
  -  ' &8>> &c/minelogin unregister <username> - &eUnregister user (Delete from database).'
  -  ' &8>> &c/minelogin lastattempt <username> - &eInformation about last login attempt.'
  -  ' &8>> &c/minelogin forcelogin <username> - &eForce user login.'
  -  ' &8>> &c/minelogin changetype <username> <true/false> - &eChange user login type (true = for paid accounts, false = for cracked players)'
  -  ' &8>> &c/minelogin changepassword <username> <password> - &eChange user password.'
  -  ' &8>> &c/minelogin migration <stop/MINELOGIN/AUTHME/FASTLOGIN/DYNAMICBUNGEEAUTH> - &eMigration users from other plugins.'
  -  ' &8>> &c/minelogin geoip <check/add/remove> <address (IPv4)> - &eManage GeoIP whitelist.'
afterLoginServerNoResponding: ' &cAfter login server is no responding.'
alreadyLogin: ' &8>> &cYou are already logged in!'
alreadyRegistered: ' &8>> &cYou are already registered!'
apisAreNotResponding: '&cAPIs are not responding!'
argumentIsNotBoolean: ' &8>> &cArgument is not boolean!'
badNickLength: '&cIncorrect nick length.'
badUniqueIDFormat: ' &8>> &cUUID format is: &exxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
changeEmailAddressCommand: ' &8>> &cUse &e/email <old-email-address> <new-email-address> &cto change him!'
changePasswordCommand: ' &8>> &7Change your password: &e/changepass <old-password> <new-password>'
commandConfirm: ' &8>> &cPlease run this command again to confirm!'
commandsOnBossBar:
  loginCommand: '&7Login with &e/login <password>'
  registerCommand: '&7Set your password: &e/register <password> <password> %captcha%'
countryIsBlocked: '&cYour country is blocked!'
crackedAccountDetected: ' &8>> &cCracked account detected!'
crackedCommand: ' &8>> &7Change account type to cracked: &e/cracked <password> <repeat-password>'
doNotHavePermission: ' &8>> &cYou are not permitted to perform this command! &8(&e%permission%&8)'
errorChangeYourAccountType: ' &8>> &cAn error occured while changing account type to paid!'
incorrectCaptcha: ' &8>> &cThe code you entered is incorrect!'
incorrectEmailValidation: ' &8>> &cIncorrect email!'
incorrectOldPassword: ' &8>> &cIncorrect old password!'
incorrectPassword: ' &8>> &cIncorrect password! %use%/%max% attempts left.'
incorrectPasswordKick: ' &f&lmineLogin %new% &cToo many failed attempts! Use &e/recovery. &cNOTE: Make sure you have an email adress assigned to your account.'
incorrectPasswordRestoreInfo: ' &8>> &cLast attempt! If you forgot your password, use &e/recovery. &cNOTE: Make sure you have an email adress assigned to your account.'
invalidRecoveryCode: ' &8>> &cInvalid security code. Check your email!'
isIllegalPassword: ' &8>> &cThis password is illegal, please change.'
joinTitle:
  needLogged: '&eNeed login!'
  needRegister: '&eSet your password!'
  successLoginBySession: '&aSuccessfully logged in by session!'
  successLoginPaidAccount: '&aSuccessfully logged in! (premium account)'
  title: '&6&lmineLogin'
loginCommand: ' &8>> &7Login with &e/login <password>'
loginServerNull: '&cPlease check login server configuration.'
loginTimeout: '&cTime for logging in has expired!'
mailingIsDisabled: ' &8>> &cThis server has disabled mailing system.'
maximumPlayerAccounts: ' &8>> &cYou have reached the maximum number of accounts!'
migrationCommand:
  -  ''
  -  ' &8>> &aAvailable plugins for migration:'
  -  ' - AUTHME'
  -  ' - FASTLOGIN + AUTHME'
  -  ' - OLD MINELOGIN'
  -  ' - DYNAMICBUNGEEAUTH'
  -  ' '
  -  ' &8>> &cType your plugin and use &e/minelogin migration <AUTHME/FASTLOGIN/MINELOGIN/DYNAMICBUNGEEAUTH>'
  -  ' &8>> &cUse &e/minelogin micration stop &cto stopping migration process.'
  -  ' '
migrationPluginNull: ' &8>> &cMigration plugin is null. Use MINELOGIN, AUTHME, FASTLOGIN, DYNAMICBUNGEEAUTH'
 # Placeholders: %minimum%
minimumPasswordLength: ' &8>> &8Your password must contain more than %minimum% characters!'
needReconnectToConfirmChanged: '&aPlease reconnect to server for confirm.%new%&6&lWARNING! &cYour UUID will change!'
nickIsAlreadyOnline: '&cThis nick is already online!'
nicknameIsNotPaidAccount: ' &8>> &cYour nickname does not belong to paid account.'
noEmailConnected: ' &8>> &cThere is no e-mail address connected to this account.'
notAllowedChars: '&cYour nick contains not allowed chars!'
notLogged: ' &8>> &cYou are not logged in!'
notMatchEmails: ' &8>> &cEmails do not match, try again.'
notMatchPasswords: ' &8>> &cPasswords do not match, try again.'
paidAccountDetected: ' &8>> &cPremium account detected!'
playerIsOffline: ' &8>> &cPlayer is currently offline!'
recoveryAccountCommand: ' &8>> &cUse &e/restore <code> <new-password> <new-password>'
recoveryAccountEmailSend: ' &8>> &aAccount recovery email has been sent! Delivery process may take up to 8 minutes.'
recoveryAccountSuccess: ' &8>> &aYour account has been successfully recovered!'
registerCommand: ' &8>> &7Set your password: &e/register <password> <password> %captcha%'
repeatMigrationCommand: '&cPlease repeat migration command again.'
serverIsFull: '&cServer is full, try again later.'
successAddAddressToWhitelist: '&aSuccess add address to GeoIP whitelist.'
successChangeConnectedEmailAddress: ' &8>> &aSuccessfully changed your email address!'
successChangePassword: ' &8>> &aYour password has been changed successfully!'
successChangePasswordByAdmin: ' &8>> &a%username%''s password has been succesfully changed!'
successChangeUniqueIDByAdmin: ' &8>> &aSuccessfully change &e%username% &aunique id.'
successChangeUserType: ' &8>> &aSuccessfully changed user''s account type!'
 # Use "%type%" for account type
successChangeYourAccountType: ' &8>> &aSuccess changed account type! (paid)'
successConnectedEmailAddress: ' &8>> &aSuccess connected your email address to account!'
successDisableLoginSession: ' &8>> &aSuccessfully disabled login session!'
successEnableLoginSession: ' &8>> &aLogin session successfully enabled for %time% or until the ip address is changed.'
successForceLogin: ' &8>> &aForced login- %username%'
successLoginBySession: ' &8>> &aSuccessfully logged in by session!'
successLoginNonPremiumAccount: ' &8>> &aSuccessfully logged in! (non-premium account)'
successLoginPaidAccount: ' &8>> &aSuccessfully logged in! (premium account)'
successRegister: ' &8>> &aYou have been successfully registered!'
successRegisterByAdmin: ' &8>> &aSuccessfully registered user!'
successRemoveAddressFromWhitelist: '&aSuccess remove address from GeoIP whitelist.'
successStoppedMigration: ' &8>> &cSuccess stopped migration!'
successUnregister: '&aSuccessfully unregistered!'
successUnregisterByAdmin: ' &8>> &aSuccessfully unregistered %username%!'
tooManyConnections: '&cToo many connections! Please try again in &e%time%'
typeVariableCracked: 'Cracked'
typeVariablePaid: 'Paid'
unregisterCommand: ' &8>> &7Unregister your account &e/unregister <password> %captcha%'
useCorrectUsername: '&cUse your correct username: &e%username%'
userAlreadyHaveThisType: ' &8>> &cThis account already has this type.'
userAlreadyLogin: ' &8>> &cUser is already logged!'
userIsNotRegistered: ' &8>> &cThis user is not registered!'
userIsNull: ' &8>> &cUser is null!'
userIsRegistered: ' &8>> &cThis user is already registered!'
userLastAttempt: ' &8>> &cLast attempt this user is: &e%lastAttempt%'
userNeverJoined: ' &8>> &cUser has never joined to server.'
warningAddEmail: '&4&lIMPORTANT! &cAdd an email address to your account &e/email <email>'
