#################################################
#                    mineLogin                  #
#  The best plugin for players authentication!  #
#                                               #
#             Main configuration file           #
#                                               #
#             Config version: 1.0.0             #
#################################################

#PL: Twój klucz licencji.
#EN: Your license key.
license-key: CODE
#PL: Typ kolorowania wiadomości.
#EN: Message colouring type
#Options: LEGACY, ADVENTURE
color-formatting-type: LEGACY
#PL: Konfiguracja bazy danych.
#EN: Database configuration.
database:
  #PL: Wyłącz gdy nie chcesz dostawać informacji o zerwanym połączeniu z bazą danych.
  #EN: Turn it off if you don't want to receive information about a broken connection to the database.
  show-mysql-errors: true
  #PL: Użytkownik twojej bazy danych.
  #EN: Database username.
  username: mineLogin
  #PL: Port twojej bazy danych.
  #EN: Database port.
  port: 3306
  #PL: Baza w której ma stworzyć się tabela mineLogin.
  #EN: Database name where the mineLogin table should be created.
  base: mineLogin
  #PL: Włącz w przypadku gdy twoja baza korzysta z SSL.
  #EN: Enable if your database uses SSL.
  ssl-use: false
  #PL: Czas oczekiwania na połączenie.
  #EN: Connection timeout.
  connection-timeout: 3000
  #PL: Typ sterownika bazy danych (SQL).
  #PL: Database driver type (SQL).
  #Options: MYSQL, MARIADB
  sql-driver: MYSQL
  #PL: Hasło dostępu do twojej bazy danych.
  #EN: Database password.
  password: n.YB*CKqZ62cUk2z
  #PL: Parametr HikariCP dla maksymalnego czasu życia połączenia.
  #EN: HikariCP parameter for max connection time.
  max-life-time: 1800000
  #PL: Parametr HikariCP dla maksymalnego rozmiaru puli.
  #EN: HikariCP parameter for max pool size.
  max-pool-size: 20
  #PL: Typ bazy danych.
  #EN: Database type.
  #Options: MYSQL, H2, FLAT
  data-type: H2
  #PL: Adres twojej bazy danych.
  #EN: Database address.
  hostname: 51.83.145.95
  sll-use: false
#PL: Konfiguracja serwerów którymi dysponuje plugin.
#EN: Configuration of the servers available for the plugin
servers:
  #PL: Serwery na których gracze mają się logować.
  #EN: Servers on which the players should log in.
  login-servers:
  - v1_18_2
  #PL: Czy gracze mają być przenoszeni na jeden z serwerów podanych poniżej po zalogowaniu.
  #EN: Should the players be moved to one of the servers listed below upon login.
  change-server-after-login: true
  #PL: Czy gracze po wyrzuceniu z jednego z serwerów na sieci mają być przenoszeni na serwer
  # awaryjny. (Zależnie czy jest włączona opcja poniżej są przenoszeni na serwer logowania lub po zalogowaniu)
  #EN: Should players be moved to a fallback server after being kicked from one of the servers
  # on the network. (Depending on whether the option below is enabled they are moved to the login server or after login)
  fallback-server: true
  #PL: Serwery na które gracze mają być przeniesieni po zalogowaniu.
  #EN: Servers to which players should be transferred upon login.
  after-login-servers:
  - plots
#PL: Konfiguracja api do autoryzacji graczy.
#EN: Player authentication api configuration
apis:
  #PL: Jakiego api domyślnie powinien używać plugin do sprawdzania czy gracz jest premium.
  #EN: What api should the plugin use by default to check if the player has a paid account.
  #Options: ASHCON, CLOUDPROTECTED, MINETOOLS, MOJANG, RANDOM
  api-type: RANDOM
#PL: Konfiguracja systemu email do odzyskiwania kont przez graczy.
#EN: Player account recovery system configuration.
mailing:
  #PL: Nazwa twojego serwera w emailu.
  #EN: Your server name in the email.
  server-name: YourAddress.net
  #PL: Hasło użytkownika do serwera mailongowego.
  #EN: Email server password.
  password: koeckiartur_8df350afc5a9fcfa774a108a6384b09d
  #PL: Tytuł wysłanego emaila.
  #EN: Email title.
  email-title: Account recovery on YourAddress.net
  #PL: Adres serwera mailingowego.
  #EN: Email server address.
  server: smtp.netcorecloud.net
  #PL: Ostrzeżenie wyświetlane, gdy do konta nie został przypisany żaden adres e-mail.
  #EN: Display a warning when no email address has been assigned to the account.
  email-warning: true
  #PL: Port do serwera mailingowego.
  #EN: Email server port.
  port: 25
  #PL: Adres z którego będzie wysyłany email.
  #EN: Email address which the email will be sent from.
  sender-email: koeckiartur@pepisandbox.com
  #PL: Czy system mailingowy ma być włączony?
  #EN: Should the mailing system be enabled?
  enabled: true
  #PL: Nazwa użytkownika do serwera mailongowego.
  #EN: Email server username.
  username: koeckiartur
#PL: Konfiguracja managera motd serwera. Rekomendujemy użycie go zamiast innych pluginów na motd.
#EN: Server motd manager configuration. We recommend using it over other motd managing plugins.
server-ping:
  #PL: Konfiguracja wiadomości motd.
  #EN: Motd message configuration.
  message-of-the-day:
    #PL: Konfiguracja wiadomości.
    #EN: Message configuration
    messages:
    - '                    &#ffaf05&l m i n e L o g i n new {new} &8[&6#&8] &7Advanced
      login system.'
    - '                    &#ffaf05&l m i n e L o g i n {new} &8[&6#&8] &ehttps://minelogin.minecodes.pl/'
    #PL: Czy ta funkcja ma być włączona?
    #EN: Should this feature be enabled?
    enabled: true
  #PL: Konfiguracja niestandardowych wiadomośći po najechaniu na liste graczy online.
  #EN: Custom message configuration when hovering over the player list.
  players-info:
    #PL: Konfiguracja wiadomości.
    #EN: Message configuration.
    messages:
    - ''
    - '                      &aBuy it!'
    - ''
    - '      &ehttps://minelogin.minecodes.pl/'
    - ''
    #PL: Czy ta funkcja ma być włączona?
    #EN: Should this feature be enabled?
    enabled: true
  #PL: Niestandardwowa linijka tekstowa wzamian za ilość graczy online.
  #EN: Custom text in exchange for the number of online players.
  version-protocol:
    #PL: Czy ta funkcja ma być włączona?
    #EN: Should this feature be enabled?
    enabled: true
    #PL: Konfiguracja wiadomości.
    #EN: Message configuration.
    #Placeholders: {online}, {slots}
    message: '&eAdvanced login system for premium and cracked players.                                                    &7Online
      &e{online}&7/&c{slots} &7players'
    #PL: Protokół -1 umożliwia ustawienia niestandartowej linijki
    # tekstowej, pozostałe są pszypisane dla konkretnych wersji.
    #EN: Protocol -1 allows you to set a non-standard text
    # line, the other ones are assigned to a specific version.
    protocol: -1
#PL: Konfiguracja ustawień proxy w które integruje mineLogin.
#EN: Proxy configuration that mineLogin integrates into
proxy:
  #PL: Typ pokazywania slotów. STATIC - Statyczna liczba slotów, DYNAMIC - Gracze online + 1
  #EN: Slot show type. STATIC - Static number of slots, DYNAMIC - Online players + 1
  slots-type: STATIC
  #PL: Ilość slotów na proxy.
  #EN: Number of slots on the proxy.
  slots: 100
  #PL: Czas pomiędzy połączeniami graczy.
  #EN: Time between player connections.
  #Format: 1d, 1h, 1m, 1s or time in milliseconds.
  between-connections: '30'
#PL: Konfiguracja innych ustawień pluginu.
#EN: Other plugin settings configuration.
other-settings:
  #PL: Czy captcha ma być pokazana na chacie czy na mapie.
  #EN: Should captcha be displayed in chat or on a map.
  #Options: CHAT, MAP
  captcha-type: MAP
  #PL: Czas trwania sesji logowania gracza non-premium.
  #EN: The duration of a cracked player's login session.
  #Format: 1d, 1h, 1m or 1s
  session-active-time: 3d
  #PL: Ile czasu gracz ma na rejestracje lub logowanie?
  #EN: How much time does a player have to register or log in?
  #Format: 1d, 1h, 1m or 1s
  login-timeout: 30s
  #PL: Czy komend /lobby ma być włączona?
  #EN: Should the /lobby command be enabled?
  enabled-lobby-command: true
  #PL: Czy podczas rejestracji ma być wymagany kod captcha?
  #EN: Should a captcha code be required during registration?
  captcha: true
  #PL: Włączenie tej opcji umożliwia graczom nie tracić przedmiotów podczas zmiany logowania z non-premium na premium.
  #EN: Enabling this option allows players to not lose items when switching from cracked to premium authentication.
  offline-unique-id-system: false
  #PL: Co ile sekund ma powtarzać się komenda logowania lub rejestrowania.
  #EN: Every how many seconds should the login or logging command repeat.
  commands-repeat: 5
  #PL: Komendy dostępne dla gracza przed zalogowaniem.
  #EN: Commands list available before the player logs in.
  available-commands-before-login:
  - login
  - register
  - l
  - reg
  - restore
  - recovery
  - recoveryaccount
  #PL: Ta opcja chroni nazwy kont premium, dzięki czemu gracz non-premium nie może zająć nicku premium.
  #EN: This option protects premium account names so that a cracked player cannot take a premium nickname.
  premium-nicknames-protected: false
  #PL: Regex dla dozwolonych nikców.
  #EN: Allowed nickname regex..
  #Format: 1d, 1h, 1m or 1s
  nickname-allowed-regex: '[a-zA-Z0-9_]+'
  use-spigot-bridge: false
#PL: Konfiguracja domyślnego skina dla graczy non-premium.
#EN: Default skin configuration for cracked players.
default-skin:
  #PL: Tekstura skina, zdobędziesz ją dzięki temu linkowi https://sessionserver.mojang.com/session/minecraft/profile/TUTAJ-WPISZ-UUID?unsigned=false, musisz zmienić TUTAJ-WPISZ-UUID na uuid gracza z danym skinem.
  #EN: Skin texture, you can get it through this link https://sessionserver.mojang.com/session/minecraft/profile/PUT-UUID-HERE?unsigned=false, you need change PUT-UUID-HERE to the player's uuid with this skin.
  value: ewogICJ0aW1lc3RhbXAiIDogMTYzOTIwNTI0OTkwMiwKICAicHJvZmlsZUlkIiA6ICJkZGU4MTE1YjcwYjI0ZDU2YTllNTdiNWUzOTE0MjJhOSIsCiAgInByb2ZpbGVOYW1lIiA6ICJfYXJ0dXJlayIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8xNmVkMjEzNTAwMGZiOWYwMzMxMTIxMzkyZjFmYjUyOTFmNTJiMmNlNGFmMDJkNGFhM2JiM2U1OTUzYzU5YjMzIgogICAgfSwKICAgICJDQVBFIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8yMzQwYzBlMDNkZDI0YTExYjE1YThiMzNjMmE3ZTllMzJhYmIyMDUxYjI0ODFkMGJhN2RlZmQ2MzVjYTdhOTMzIgogICAgfQogIH0KfQ==
  #PL: Sygnatura tekstury, zdobędziesz ją z powyższego linku.
  #EN: Texture signature, you will get it from the link above.
  signature: jzHnovbTHe2Swg8W690SsnrE445ynmGVKuyTHANr+3NTfeCVkFaYw+LCkDhT2tmWwMsBtqyuo30xB0+RyS9xIrQ7c5FCFXyxjj8hwHuzkpO5GXyaO2V80Fp2SuF+tnS8h+O3NkNzzDqIq8VILGU5qcLqMVRmbSvf8TYomzXoItl7h4cW5wpLvuV7WL8YjGo9ICfmMEaA7TkjU6sHHkBc4cJfx1naWAe8hAB3C+dv7BHgm8gevm88/IE2TGugzOrk3m317H9TLCW+YM9pHk/4yKlCBxccFhH/Z5h4MCV+9YHLlz+h99+gC4tzafk68KqDtPD3aDEeSg3NNVvTSybOPZ1IctlnKtNb5GNSYXu6Jj6Ao2pxD4go1dFPWOZYvU1Cz/8fM8BqoeztqSKOXpWCWymmpk1kgqWEq2EyGMfPGxMFfAU+tDyGV+rGluumH/XOjmQDvNQePL7aZUzIem0Y1Yqrsu2EmLgbF/Gw+cB2NbJ7erOnpRUQafYvoTueA1rDgHF4hyl+2Dr5V1S9GQPAvzZLbcvX/7UHeo0mpTobGBeWP7Iv4vFZSRuSJ3tKr7jkgFwHtaSlRUNm75QipjOujsnOv8UG5sDks38fLnc1KZFz2RbrlRNvl0gGQULysWGVRsB03KrLEzLJcTw3gYGt8z7mjx2O42T2d8MIGCBswz0=
  #PL: Czy domyślny skin dla kont non-premium ma być włączony?
  #EN: Should the default skin for non-premium accounts be enabled?
  enabled: true
#PL: Konfiguracja limitów w pluginie.
#EN: Plugin limits configuration.
limits:
  #PL: Maksymalna ilość prób logowania.
  #EN: Maximum number of login attempts.
  login-attempts: 3
  #PL: Maksymalna ilośc kont zarejestrowana na jeden adres ip.
  #EN: Maximum number of accounts registered to one ip address.
  accounts-per-address: 2
#PL: Konfiguracja powiadomień na title podczas dołączania.
#EN: On join title notifications configuration.
notifications-title:
  #PL: 
  #EN: 
  success-premium-login: ' &8[&6#&8] &aSuccess premium logged in!'
  #PL: Czy powiadomienia title mają być włączone.
  #EN: Whether title notifications should be enabled.
  enabled: true
  #PL: 
  #EN: 
  success-register: ' &8[&6#&8] &aSuccess account register.'
  #PL: 
  #EN: 
  need-logged: ' &8[&6#&8] &aYou are need login in.'
  #PL: Ile sekund ma znikać.
  #EN: How many seconds should it disappear for.
  fade-out: 1
  #PL: 
  #EN: 
  success-cracked-login: ' &8[&6#&8] &aSuccess cracked logged in!'
  #PL: 
  #EN: 
  need-registered: ' &8[&6#&8] &aYou are need register.'
  notification-title: '&#ffaf05&lm i n e L o g i n'
  #PL: Ile sekund ma pozostać na ekranie.
  #EN: How many seconds should it remain on the screen.
  stay: 3
  #PL: Ile sekund ma pojawiać.
  #EN: How many seconds should it appear for.
  fade-in: 1
  #PL: 
  #EN: 
  success-session-login: ' &8[&6#&8] &aSuccess session logged in!'
#PL: Konfiguracja bezpieczeństwa haseł.
#EN: Password security configuration.
passwords-security:
  #PL: Minimalna długość hasła która gracz musi ustawić.
  #EN: The minimum password length that a player must set.
  minimum-password-length: 6
  #PL: Czy hasła mają być dodatkowo zabezpieczone salt.
  #EN: Whether passwords should be additionally protected with salt.
  salt-for-passwords: false
  #PL: Jakiego algorytmu hashowania ma używać plugin.
  #EN: What hashing algorithm should the plugin use.
  #Options: BCRYPT, SHA512, SHA256 and MD5
  hash-type: BCRYPT
  #PL: Lista niedozwolonych haseł.
  #EN: List of disallowed passwords.
  disallowed-passwords:
  - password
  - password123
  - haslo123
  - haslo1
  - dick123
  - pussy1
  - pussy123
#PL: Konfiguracji widoczności komend na boss bar.
#EN: Boss bar command visibility configuration.
boss-bar-commands:
  #PL: Styl BossBara.
  #EN: BossBar style.
  #Options: PROGRESS, NOTCHED_6, NOTCHED_10, NOTCHED_12, NOTCHED_20
  overlay: PROGRESS
  #PL: Wiadomość jeśli gracz potrzebuje się zarejestrować.
  #EN: Message if the player has to register.
  register-command: ' &8[&6#&8] &6Use login command: &e/register <password> <password>
    {captcha} &8[&6#&8] '
  #PL: Czy pokazywanie komend na boss bar ma być włączone?
  #EN: Should the command displayed on the boss bar be turned on?
  enabled: true
  #PL: Kolor BossBara.
  #EN: BossBar color.
  color: YELLOW
  #PL: Wiadomość jeśli gracz potrzebuje się zalogować.
  #EN: Message if the player has to log in.
  login-command: ' &8[&6#&8] &6Use login command: &e/login 1 <password> {2fa} &8[&6#&8] '
#PL: Konfiguracja geo lokalizacji adresów ip.
#EN: IP address geo location configuration.
geo-location:
  #PL: Czy geo lokalizacja adresów ip ma być włączona?
  #EN: Should ip address geo localization be enabled?
  enabled: false
  #PL: Krajowe kody iso.
  #EN: Country iso codes.
  #List: https://en.wikipedia.org/wiki/ISO_3166-1
  available-countries:
  - PL
  - FR
  - EN
  - US
#PL: Konfiguracja cachowania użytkowników.
#EN: User caching configuration.
cache:
  #PL: Po jakim czasie user ma być usunięty z cachu od momentu wyścia z serwera. Czas podany w minutach.
  #EN: After how long the user be removed from cache after leaving the server. Time in minutes.
  expire-after-leave: 1
  expire-after-access: 1
  maximum-pool: 150
#PL: Konfiguracja debugów w konsoli.
#EN: Console debug configuration.
debugs:
  #PL: Informacje dla developera.
  #EN: Developer information.
  development: true
  #PL: Informacje o przez jakie api został sprawdzony status gracza.
  #EN: Information about which api was used to check a player's status.
  paid-check: true
  #PL: Informacje o wysłanych aktualizacjach użytkowników w bazie.
  #EN: Information about user updates in the database.
  users-update: true
#PL: Konfiguracja dwuetapowej weryfikacji.
#EN: Two-step verification configuration.
verification:
  enabled: true
#PL: Konfiguracja pokazywania głowy gracza w wiadomości powitalnej.
#EN: Configuration for showing the player's head in the welcome message.
welcome-picture-head:
  #PL: Dla jakich graczy powinna być pokazywana głowa w wiadomości powitalnej.
  #EN: For which players should the head be displayed to in the welcome message.
  display-type: ALL_PLAYERS
  #PL: Czy pokazywanie głowy gracza w wiadomości powitalnej ma być włączone?
  #EN: Should the player's head be shown in the welcome message?
  enabled: true
#PL: Token autoryzacyjny dla twoich podserwerów.
#EN: The authorization token for your subservers.
authentication-token: w1afxGfh6yyLmHYzHjyYkvBgOJ8SRQzTWOqz3ecO0C8ci8m4ijR1Gm72yImBnuYP
